sudo : required
services:
  - docker

before_install:
  - docker build -t tomerfisher/docker-react -f Dockerfile.dev .

script:
  - docker run tomerfisher/docker-react npm run test -- --coverage --watchAll=false
